name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make build
      run: make

    - name: DEBUG - back to root
      run: cd

    - name: DEBUG - list
      run: ls

    - name: check in pizza time
      run: cd PizzaTimeSpiceRunners

    - name: list again
      run: ls
